// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig2_Addstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig2_Addstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202512231754051_mig2_Addstatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
